### ISSUE TITLE
Another upsd.users file location

### ISSUE THREAD

**Issue by mbv06** [renatopanda/synology-nas-beeper#2]
Hello,
I'm using ds620slim with DSM7.1.1 and for some reasons **_upsd.users_** located under **_/etc/ups_** instead of **_/usr/syno/etc/ups_**
```
# ls /usr/syno/etc/ups/
synoups.conf

# ls /etc/ups/
nutscan-usb.h  ups.conf  upsd.conf  upsd.users  upsmon.conf  upssched.conf
```
As result, creation file under **_/usr/syno/etc/ups_** doesn't create any effect and I get **ERR ACCESS-DENIED** from telnet

After modification of the **_/etc/ups/upsds.users_** file - everything is works :)

**Comment by renatopanda** [comment]
Thanks for the update!
