### ISSUE TITLE
Wrong path for Python interpreter in DSM7

### ISSUE THREAD

**Issue by balaji-dutt** [renatopanda/synology-nas-beeper#4]
Hello,

I came across this repo while looking for an alternative to the missing `upscmd` on DSM. However, with DSM7 I got the error that it could not find `python2`. I eventually figured out that in DSM7 `python2` has been moved to `/usr/local/bin/python2`

Perhaps you want to update the script to use `#!/usr/bin/env python2` instead of calling the path directly?

**Comment by renatopanda** [comment]
Nice catch @balaji-dutt, I haven't tested it for long so was unaware of this.
There is also python3 available (at least in mine) so it might be a good idea to update it from v2 to v3 in the future.
